title: "RENO WARNER"
description: "A showcase of my projects"
baseurl: "" # Keep it empty if using a GitHub Pages domain
url: "https://warner.industries" # Change if using a custom domain
remote_theme: minimal-mistakes-jekyll
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

collections:
  projects:
    output: true
    permalink: /projects/:path/

navigation:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "Articles"
    url: "/articles/"

header:
  image: "/assets/images/hero.jpg"

footer:
  links:
    - title: "GitHub"
      url: "https://github.com/RENO-WARNER"
    - title: "LinkedIn"
      url: "https://www.linkedin.com/in/reno-warner/"